In [1]:
import pandas as pd

df = pd.read_csv("employee_turnover_dataset.csv")

print(df.shape)

df.head()

(6500, 30)

,employee_id,age,gender,marital_status,education_level,years_of_experience,job_role,department,job_level,employment_type,...,promotion_last_2yrs,job_satisfaction,work_life_balance,engagement_score,training_hours,internal_mobility,tenure_years,time_since_last_promotion,time_in_current_role,attrition_status
0,E00001,50,Male,Married,Bachelor,6.6,Engineer,IT,Mid,Full-time,...,Yes,3,2,58.85,38,Yes,4.1,52,24,Stayed
1,E00002,36,Female,Single,PhD,10.6,Engineer,HR,Executive,Contract,...,No,3,2,62.73,18,No,17.2,10,44,Stayed
2,E00003,29,Male,Single,Bachelor,19.5,Sales,HR,Senior,Full-time,...,Yes,1,5,88.44,11,Yes,10.8,11,2,Stayed
3,E00004,42,Male,Married,High School,11.5,Engineer,IT,Entry,Contract,...,No,5,3,95.30,8,Yes,19.7,48,16,Stayed
4,E00005,40,Male,Single,Diploma,15.1,Sales,HR,Mid,Contract,...,No,2,5,65.74,46,No,12.9,59,16,Stayed

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6500 entries, 0 to 6499
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   employee_id                6500 non-null   object
 1   age                        6500 non-null   int64
 2   gender                     6500 non-null   object
 3   marital_status             6500 non-null   object
 4   education_level            6500 non-null   object
 5   years_of_experience        6500 non-null   float64
 6   job_role                   6500 non-null   object
 7   department                 6500 non-null   object
 8   job_level                  6500 non-null   object
 9   employment_type            6500 non-null   object
 10  work_location              6500 non-null   object
 11  reporting_manager_score    6500 non-null   float64
 12  monthly_income             6500 non-null   int64
 13  bonus_percentage           6500 non-null   float64
 14  stock_option_level         4837 non-null   object
 15  benefits_satisfaction      6500 non-null   int64
 16  performance_rating         6500 non-null   int64
 17  projects_completed         6500 non-null   int64
 18  average_work_hours         6500 non-null   float64
 19  absenteeism_days           6500 non-null   int64
 20  promotion_last_2yrs        6500 non-null   object
 21  job_satisfaction           6500 non-null   int64
 22  work_life_balance          6500 non-null   int64
 23  engagement_score           6500 non-null   float64
 24  training_hours             6500 non-null   int64
 25  internal_mobility          6500 non-null   object
 26  tenure_years               6500 non-null   float64
 27  time_since_last_promotion  6500 non-null   int64
 28  time_in_current_role       6500 non-null   int64
 29  attrition_status           6500 non-null   object
dtypes: float64(6), int64(11), object(13)
memory usage: 1.5+ MB

In [3]:
df.isnull().sum()

employee_id                     0
age                             0
gender                          0
marital_status                  0
education_level                 0
years_of_experience             0
job_role                        0
department                      0
job_level                       0
employment_type                 0
work_location                   0
reporting_manager_score         0
monthly_income                  0
bonus_percentage                0
stock_option_level           1663
benefits_satisfaction           0
performance_rating              0
projects_completed              0
average_work_hours              0
absenteeism_days                0
promotion_last_2yrs             0
job_satisfaction                0
work_life_balance               0
engagement_score                0
training_hours                  0
internal_mobility               0
tenure_years                    0
time_since_last_promotion       0
time_in_current_role            0
attrition_status                0
dtype: int64

In [4]:
df['attrition_status'].value_counts()

attrition_status
Stayed    4527
Left      1973
Name: count, dtype: int64

In [5]:
df.describe()

,age,years_of_experience,reporting_manager_score,monthly_income,bonus_percentage,benefits_satisfaction,performance_rating,projects_completed,average_work_hours,absenteeism_days,job_satisfaction,work_life_balance,engagement_score,training_hours,tenure_years,time_since_last_promotion,time_in_current_role
count,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000,6500.000000
mean,40.613692,18.134985,5.494385,82105.586308,14.996962,2.997231,2.978769,7.042462,50.238446,9.598000,2.982308,2.992462,55.178288,49.343846,10.135615,29.670462,29.274308
std,10.876151,9.967870,2.586650,38756.215381,8.635161,1.423969,1.426405,4.308111,11.664512,5.759537,1.426184,1.402119,25.922931,28.689965,5.661588,17.302883,17.442231
min,22.000000,0.500000,1.000000,15013.000000,0.000000,1.000000,1.000000,0.000000,30.000000,0.000000,1.000000,1.000000,10.000000,0.000000,0.500000,0.000000,0.000000
25%,31.000000,9.700000,3.300000,48769.000000,7.680000,2.000000,2.000000,3.000000,40.000000,5.000000,2.000000,2.000000,32.557500,25.000000,5.200000,15.000000,14.000000
50%,41.000000,18.200000,5.500000,81479.500000,14.850000,3.000000,3.000000,7.000000,50.400000,10.000000,3.000000,3.000000,55.385000,49.000000,9.950000,30.000000,29.000000
75%,50.000000,26.700000,7.700000,115587.250000,22.490000,4.000000,4.000000,11.000000,60.600000,15.000000,4.000000,4.000000,77.790000,74.000000,15.100000,45.000000,45.000000
max,59.000000,35.000000,10.000000,149988.000000,30.000000,5.000000,5.000000,14.000000,70.000000,19.000000,5.000000,5.000000,99.960000,99.000000,20.000000,59.000000,59.000000

In [6]:
df.columns

Index(['employee_id', 'age', 'gender', 'marital_status', 'education_level',
       'years_of_experience', 'job_role', 'department', 'job_level',
       'employment_type', 'work_location', 'reporting_manager_score',
       'monthly_income', 'bonus_percentage', 'stock_option_level',
       'benefits_satisfaction', 'performance_rating', 'projects_completed',
       'average_work_hours', 'absenteeism_days', 'promotion_last_2yrs',
       'job_satisfaction', 'work_life_balance', 'engagement_score',
       'training_hours', 'internal_mobility', 'tenure_years',
       'time_since_last_promotion', 'time_in_current_role',
       'attrition_status'],
      dtype='object')

In [7]:
df = df.drop('employee_id', axis=1)

df.head()

,age,gender,marital_status,education_level,years_of_experience,job_role,department,job_level,employment_type,work_location,...,promotion_last_2yrs,job_satisfaction,work_life_balance,engagement_score,training_hours,internal_mobility,tenure_years,time_since_last_promotion,time_in_current_role,attrition_status
0,50,Male,Married,Bachelor,6.6,Engineer,IT,Mid,Full-time,Hybrid,...,Yes,3,2,58.85,38,Yes,4.1,52,24,Stayed
1,36,Female,Single,PhD,10.6,Engineer,HR,Executive,Contract,Onsite,...,No,3,2,62.73,18,No,17.2,10,44,Stayed
2,29,Male,Single,Bachelor,19.5,Sales,HR,Senior,Full-time,Remote,...,Yes,1,5,88.44,11,Yes,10.8,11,2,Stayed
3,42,Male,Married,High School,11.5,Engineer,IT,Entry,Contract,Onsite,...,No,5,3,95.30,8,Yes,19.7,48,16,Stayed
4,40,Male,Single,Diploma,15.1,Sales,HR,Mid,Contract,Remote,...,No,2,5,65.74,46,No,12.9,59,16,Stayed

In [8]:
df['stock_option_level'].value_counts(dropna=False)

stock_option_level
NaN       1663
High      1638
Medium    1617
Low       1582
Name: count, dtype: int64

In [9]:
df['stock_option_level'] = df['stock_option_level'].fillna('Unknown')

df['stock_option_level'].value_counts(dropna=False)

stock_option_level
Unknown    1663
High       1638
Medium     1617
Low        1582
Name: count, dtype: int64

In [10]:
df['attrition_status'] = df['attrition_status'].map({
    'Stayed': 0,
    'Left': 1
})

df['attrition_status'].value_counts()

attrition_status
0    4527
1    1973
Name: count, dtype: int64

In [11]:
df.select_dtypes(include='object').columns

Index(['gender', 'marital_status', 'education_level', 'job_role', 'department',
       'job_level', 'employment_type', 'work_location', 'stock_option_level',
       'promotion_last_2yrs', 'internal_mobility'],
      dtype='object')

In [12]:
df = pd.get_dummies(df, drop_first=True)

df.head()

,age,years_of_experience,reporting_manager_score,monthly_income,bonus_percentage,benefits_satisfaction,performance_rating,projects_completed,average_work_hours,absenteeism_days,...,job_level_Mid,job_level_Senior,employment_type_Full-time,work_location_Onsite,work_location_Remote,stock_option_level_Low,stock_option_level_Medium,stock_option_level_Unknown,promotion_last_2yrs_Yes,internal_mobility_Yes
0,50,6.6,9.4,31966,5.12,4,5,8,41.6,7,...,True,False,True,False,False,False,False,False,True,True
1,36,10.6,6.2,117423,26.66,1,3,14,46.6,1,...,False,False,False,True,False,False,False,True,False,False
2,29,19.5,3.1,78989,1.15,2,3,1,43.6,7,...,False,True,True,False,True,True,False,False,True,True
3,42,11.5,6.2,39548,28.30,4,2,10,64.1,13,...,False,False,False,True,False,False,True,False,False,True
4,40,15.1,8.8,117025,11.40,5,1,6,46.8,9,...,True,False,False,False,True,False,False,True,False,False

In [13]:
X = df.drop('attrition_status', axis=1)

y = df['attrition_status']

print(X.shape)
print(y.shape)

(6500, 43)
(6500,)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5200, 43)
(1300, 43)
(5200,)
(1300,)

In [15]:
X_train.dtypes.value_counts()

bool       26
int64      11
float64     6
Name: count, dtype: int64

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

log_model = LogisticRegression(max_iter=5000)

log_model.fit(X_train, y_train)

y_pred = log_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7069230769230769

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [17]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

[[919   0]
 [381   0]]
              precision    recall  f1-score   support

           0       0.71      1.00      0.83       919
           1       0.00      0.00      0.00       381

    accuracy                           0.71      1300
   macro avg       0.35      0.50      0.41      1300
weighted avg       0.50      0.71      0.59      1300

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("Random Forest Accuracy:",
      accuracy_score(y_test, rf_pred))

Random Forest Accuracy: 0.7076923076923077

In [19]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, rf_pred))

print(classification_report(y_test, rf_pred))

[[919   0]
 [380   1]]
              precision    recall  f1-score   support

           0       0.71      1.00      0.83       919
           1       1.00      0.00      0.01       381

    accuracy                           0.71      1300
   macro avg       0.85      0.50      0.42      1300
weighted avg       0.79      0.71      0.59      1300

In [20]:
print(y.value_counts())

print(y_train.value_counts())

print(y_test.value_counts())

attrition_status
0    4527
1    1973
Name: count, dtype: int64
attrition_status
0    3608
1    1592
Name: count, dtype: int64
attrition_status
0    919
1    381
Name: count, dtype: int64

In [21]:
import pandas as pd

importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
})

importance_df = importance_df.sort_values(
    by='Importance',
    ascending=False
)

print(importance_df.head(15))

                      Feature  Importance
12           engagement_score    0.061816
4            bonus_percentage    0.061097
3              monthly_income    0.060341
8          average_work_hours    0.059025
1         years_of_experience    0.058472
14               tenure_years    0.055310
2     reporting_manager_score    0.055243
13             training_hours    0.053581
15  time_since_last_promotion    0.052250
16       time_in_current_role    0.051797
0                         age    0.050708
9            absenteeism_days    0.043198
7          projects_completed    0.038924
6          performance_rating    0.024239
11          work_life_balance    0.024186

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

rf_balanced = RandomForestClassifier(
    n_estimators=300,
    class_weight='balanced',
    random_state=42
)

rf_balanced.fit(X_train, y_train)

pred_balanced = rf_balanced.predict(X_test)

print(confusion_matrix(y_test, pred_balanced))
print(classification_report(y_test, pred_balanced))

[[919   0]
 [381   0]]
              precision    recall  f1-score   support

           0       0.71      1.00      0.83       919
           1       0.00      0.00      0.00       381

    accuracy                           0.71      1300
   macro avg       0.35      0.50      0.41      1300
weighted avg       0.50      0.71      0.59      1300

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))